spring:
  datasource:
    url: ${SECUREPAY_DATABASE_URL}
    username: ${SECUREPAY_DATABASE_USERNAME}
    password: ${SECUREPAY_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
securepay:
  security:
    jwt-secret: ${SECUREPAY_JWT_SECRET}
