CREATE TABLE payments (
    id UUID PRIMARY KEY,
    customer_id VARCHAR(128) NOT NULL,
    merchant_id VARCHAR(128) NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT payments_amount_positive CHECK (amount > 0)
);

CREATE INDEX payments_customer_id_idx ON payments (customer_id);

CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    payment_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT idempotency_records_customer_key_unique UNIQUE (customer_id, idempotency_key),
    CONSTRAINT idempotency_records_payment_fk FOREIGN KEY (payment_id) REFERENCES payments (id)
);
